# Generated by Django 3.1.6 on 2021-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vouchers',
            },
        ),
    ]
