# Generated by Django 3.1.6 on 2021-02-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagmodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='bagtype',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size_name',
        ),
    ]
