# Generated by Django 3.1.6 on 2021-02-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagmodel',
            name='video',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendations',
        ),
    ]
