# Generated by Django 3.1.6 on 2021-02-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagmodel',
            name='video',
        ),
    ]
