# Generated by Django 3.1.6 on 2021-02-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_bagmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
