# Generated by Django 3.1.6 on 2021-02-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('voucher', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_country', models.CharField(max_length=100)),
                ('billing_first_name', models.CharField(max_length=100)),
                ('billing_last_name', models.CharField(max_length=100)),
                ('billing_street_number', models.CharField(max_length=100)),
                ('billing_additional_address', models.CharField(max_length=100, null=True)),
                ('billing_district', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_postal_code', models.CharField(max_length=100)),
                ('billing_phone_number', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_street_number', models.CharField(max_length=100)),
                ('shipping_additional_address', models.CharField(max_length=100, null=True)),
                ('shipping_district', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=100)),
                ('shipping_phone_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_information', to='user.user')),
            ],
            options={
                'db_table': 'address_information',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.addressinformation')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.orderstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.product')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='voucher.voucher')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
