# Generated by Django 3.1.6 on 2021-02-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210219_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
