# Generated by Django 3.1.6 on 2021-02-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.orderstatus'),
        ),
    ]
