# Generated by Django 3.1.6 on 2021-02-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cart', '0008_auto_20210219_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_additional_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_street_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_additional_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street_number',
        ),
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_country', models.CharField(max_length=100)),
                ('billing_first_name', models.CharField(max_length=100)),
                ('billing_last_name', models.CharField(max_length=100)),
                ('billing_street_number', models.CharField(max_length=100)),
                ('billing_additional_address', models.CharField(max_length=100, null=True)),
                ('billing_district', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_postal_code', models.CharField(max_length=100)),
                ('billing_phone_number', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_street_number', models.CharField(max_length=100)),
                ('shipping_additional_address', models.CharField(max_length=100, null=True)),
                ('shipping_district', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=100)),
                ('shipping_phone_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_information', to='user.user')),
            ],
            options={
                'db_table': 'address_information',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.addressinformation'),
        ),
    ]
