# Generated by Django 3.1.6 on 2021-02-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210219_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinformation',
            name='user',
        ),
    ]
