# Generated by Django 3.1.6 on 2021-02-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cart', '0010_remove_addressinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinformation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='address_information', to='user.user'),
        ),
    ]
