# Generated by Django 3.1.7 on 2021-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20210219_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinformation',
            name='is_same',
            field=models.BooleanField(default=True),
        ),
    ]
