# Generated by Django 3.1.6 on 2021-02-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
        ('product', '0002_auto_20210218_0155'),
        ('cart', '0012_auto_20210219_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='voucher.voucher'),
        ),
    ]
