# Generated by Django 3.1.6 on 2021-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210223_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinformation',
            name='is_same',
            field=models.BooleanField(),
        ),
    ]
