# Generated by Django 3.1.6 on 2021-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=2000)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('is_anonymous', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
